# Development Override - Hot Reload için
# Kullanım: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d

services:
  opensips-ai-voice-connector:
    volumes:
      # Source code hot reload için mount
      - ./src:/app/src
      - ./cfg:/app/cfg
      - ./test_audio:/app/test_audio
      - ./logs:/app/logs
    environment:
      # Development ayarları
      - DEBUG_MODE=true
      - LOG_LEVEL=DEBUG
      - TEST_MODE=false
      - PYTHONPATH=/app
      # Hot reload için Python unbuffered output
      - PYTHONUNBUFFERED=1
      # Development mode flag
      - DEVELOPMENT_MODE=true
    # Development için container'ı her seferinde rebuild etme
    build:
      context: .
      dockerfile: Dockerfile
      # Cache'i kullan ama source'u her zaman fresh tut
    # Restart policy - development'ta kod hatası olduğunda sürekli restart olmasın
    restart: "no" 