version: '3.8'

services:
  # OpenSIPS AI Voice Connector (opensips-ai-voice-connector - Sizin Python uygulamanız)
  opensips-ai-voice-connector:
    build: . # Dockerfile'ın bulunduğu dizin (proje kök dizini varsayıldı)
    container_name: opensips-ai-voice-connector-oavc
    ports:

      # Gelen istekler için TCP port 8088'i host'a map'leyin
      - "8088:8088/tcp"
      - "8089:8089/tcp"
      # RTP portlarını UDP olarak map'le
      - "35000-35003:35000-35003/udp"
      # Not: MI (8088) ve Event (35010) portları sadece diğer konteynerlerce
      # erişileceği için host'a maplenmesi genellikle GEREKMEZ.
      # Ancak, isteğiniz üzerine TCP 8088'i dışarıya açıyoruz.
    volumes:
      # Genel yapılandırma dosyasını konteynere bağla
      - ./cfg/opensips-ai-voice-connector.ini:/app/cfg/opensips-ai-voice-connector.ini
    environment:
      # Vosk sunucusuna erişim için servis adını kullanın      # Ana yapılandırma dosyasının yolunu belirtin
      - CONFIG_FILE=/app/cfg/opensips-ai-voice-connector.ini
      - PYTHONPATH=/app

    networks:
      - opensips_network
    depends_on:
      - opensips
      - vosk-server # opensips-ai-voice-connector başlamadan önce rtpproxy ve vosk'un hazır olmasını bekle
      - piper-tts-server
    restart: unless-stopped # Konteyner durursa yeniden başlatmayı dene

  # OpenSIPS Servisi
  opensips:
    # Seçenek 1: Hazır OpenSIPS imajı kullanın (versiyonu ihtiyacınıza göre seçin)
    image: opensips/opensips:3.6
    # Seçenek 2: Eğer OpenSIPS için kendi Dockerfile'ınız varsa:
    # build: ./path/to/opensips/docker/context # Gerçek yolu belirtin
    container_name: opensips
    ports:
      # Kubernetes tanımına göre portlar
      - "5060:5060/udp" # Standart SIP (UDP)
      - "8080:8080/udp" # SIP Alternatif (UDP)
      - "8088:8088/udp" # MI Datagram (UDP)
    volumes:
      # Güncellenmiş opensips.cfg dosyasını konteynere bağlayın
      - ./cfg/opensips.cfg:/etc/opensips/opensips.cfg
    networks:
      - opensips_network

    restart: unless-stopped

  # Vosk STT Servisi
  vosk-server:
    image: dehalokmansahin/vosk-server:latest # Örnek Vosk imajı
    container_name: vosk-server
    ports:
      # Vosk WebSocket portunu host'a map'leyin
      - "2700:2700"
    networks:
      - opensips_network
    restart: unless-stopped

  piper-tts-server:
    image: piper-tts-server:py311
    container_name: piper-tts-server
    ports:
      - "8000:8000"
      - "8080:8080"
    networks:
      - opensips_network
    restart: unless-stopped

  llm-turkish-server:
    image: dehalokmansahin/llm-turkish-server:latest
    container_name: llm-turkish-server
    ports:
      - "8765:8765"
    networks:
      - opensips_network
    restart: unless-stopped
networks:
  opensips_network:
    driver: bridge # Konteynerlerin birbirleriyle konuşabilmesi için ağ
