apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensips-ai-voice-connector
  labels:
    app: oavc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oavc
  template:
    metadata:
      labels:
        app: oavc
    spec:
      containers:
      - name: oavc
        # IMPORTANT: Replace <your-project> with your OpenShift project name
        # and ensure this image exists in the internal registry or another accessible registry.
        # Example: image: image-registry.openshift-image-registry.svc:5000/my-project/opensips-ai-voice-connector-oavc:latest
        image: image-registry.openshift-image-registry.svc:5000/<your-project>/opensips-ai-voice-connector-oavc:latest
        # Or use an externally hosted image:
        # image: your-dockerhub-user/opensips-ai-voice-connector-oavc:latest
        ports:
        - containerPort: 8088
          name: sip-udp
          protocol: UDP
        # Define the RTP port range
        - containerPort: 35000
          name: rtp-start
          protocol: UDP
        # Kubernetes doesn't directly support ranges in containerPort, 
        # but defining the start port is common practice. 
        # The application must bind within the intended range (35000-35100 here).
        # The corresponding Service will need to handle the range.
        env:
          - name: CONFIG_FILE
            value: /app/cfg/opensips-ai-voice-connector.ini
          - name: PYTHONPATH
            value: /app
          # Override Vosk URL to use the Kubernetes service name
          - name: VOSK_WS_URL
            value: ws://vosk-server:2700
          # Specify SIP port used by the application
          - name: SIP_PORT
            value: "8088"
        volumeMounts:
        - name: config-volume
          mountPath: /app/cfg
      volumes:
      - name: config-volume
        configMap:
          name: opensips-ai-voice-connector 