# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xa1\x01\n\x13HealthCheckResponse\x12\x39\n\x06status\x18\x01 \x01(\x0e\x32).common.HealthCheckResponse.ServingStatus\"O\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x12\x13\n\x0fSERVICE_UNKNOWN\x10\x03\"?\n\rErrorResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x03 \x01(\t\"P\n\tAudioData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x04 \x01(\t\">\n\x08TextData\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\"M\n\x0bSessionInfo\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"\xca\x01\n\rServiceStatus\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x12\n\nis_healthy\x18\x02 \x01(\x08\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x04 \x01(\x03\x12\x35\n\x08metadata\x18\x05 \x03(\x0b\x32#.common.ServiceStatus.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVICESTATUS_METADATAENTRY']._loaded_options = None
  _globals['_SERVICESTATUS_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_HEALTHCHECKREQUEST']._serialized_start=24
  _globals['_HEALTHCHECKREQUEST']._serialized_end=61
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=64
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=225
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=146
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=225
  _globals['_ERRORRESPONSE']._serialized_start=227
  _globals['_ERRORRESPONSE']._serialized_end=290
  _globals['_AUDIODATA']._serialized_start=292
  _globals['_AUDIODATA']._serialized_end=372
  _globals['_TEXTDATA']._serialized_start=374
  _globals['_TEXTDATA']._serialized_end=436
  _globals['_SESSIONINFO']._serialized_start=438
  _globals['_SESSIONINFO']._serialized_end=515
  _globals['_SERVICESTATUS']._serialized_start=518
  _globals['_SERVICESTATUS']._serialized_end=720
  _globals['_SERVICESTATUS_METADATAENTRY']._serialized_start=673
  _globals['_SERVICESTATUS_METADATAENTRY']._serialized_end=720
# @@protoc_insertion_point(module_scope)
